### ISSUE TITLE
stop showing the next bus schedule for each bus stop

### ISSUE THREAD

**Issue by tangzh** [cardinaldevs/marguerite-ios#79]

**Comment by kevincon** [comment]
Hi @tangzh, thanks for opening an issue. Just to confirm what's happening for you, you're saying that all of the stops say "Today's service complete"?

We've had a few reports from other users of the same thing, and removing the app from your device and reinstalling it from the App Store seems to resolve the issue. Can you let me know if that works for you or not?

Also, in an effort to fix this bug, can you let me know if you did anything to your phone recently like restore it from a backup or upgrade the OS? I'm not sure yet why this is only happening to some users...

**Comment by tangzh** [comment]
Hi @kevincon , thanks for the quick reply! And removing and reinstalling did solve the problem!!

I think what's happening to me is also what happening to others: all of the stops say "Today's service complete". Before this problem, I did upgrade my phone from 7.X.X to the newest 8.1.1. I guess this might be the reason you suspect? Hope this helps!
